apiVersion: apps/v1
kind: Deployment
metadata:
  name: fets-desktop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fets-desktop
  template:
    metadata:
      labels:
        app: fets-desktop
    spec:
      hostname: fets-desktop
      containers:
      - name: fets-desktop
        image: ghcr.io/selkies-project/nvidia-glx-desktop:latest
        env:
        - name: TZ
          value: "UTC"
        - name: DISPLAY_SIZEW
          value: "1920"
        - name: DISPLAY_SIZEH
          value: "1080"
        - name: DISPLAY_REFRESH
          value: "60"
        - name: DISPLAY_DPI
          value: "96"
        - name: DISPLAY_CDEPTH
          value: "24"
        - name: VIDEO_PORT
          value: "DFP"
        - name: PASSWD
          valueFrom:
            secretKeyRef:
              name: my-pass
              key: my-pass
        - name: SELKIES_ENCODER
          value: "nvh264enc"
        - name: SELKIES_ENABLE_RESIZE
          value: "false"
        - name: SELKIES_VIDEO_BITRATE
          value: "8000"
        - name: SELKIES_FRAMERATE
          value: "60"
        - name: SELKIES_AUDIO_BITRATE
          value: "128000"
        - name: SELKIES_ENABLE_BASIC_AUTH
          value: "true"
        - name: SELKIES_TURN_REST_URI
          value: "http://turn-rest.nrp-nautilus.io"
        - name: SELKIES_TURN_PROTOCOL
          value: "tcp"
        # Try disabling TLS first to see if that fixes the issue
        - name: SELKIES_TURN_TLS
          value: "false"
        - name: SELKIES_CONGESTION_CONTROL
          value: "true"
        # Force GNOME desktop environment
        - name: XDG_CURRENT_DESKTOP
          value: "ubuntu:GNOME"
        - name: XDG_SESSION_DESKTOP
          value: "ubuntu"
        - name: XDG_SESSION_TYPE
          value: "x11"
        - name: DESKTOP_SESSION
          value: "ubuntu"
        - name: GDMSESSION
          value: "ubuntu"
        # Disable problematic services
        - name: PULSE_RUNTIME_PATH
          value: "/tmp/pulse"
        - name: SELKIES_DEBUG
          value: "true"
        stdin: true
        tty: true
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        resources:
          limits:
            memory: 64Gi
            cpu: "16"
            nvidia.com/gpu: 1
          requests:
            memory: 4Gi
            cpu: "2"
        volumeMounts:
        - mountPath: /dev/shm
          name: dshm
        - mountPath: /cache
          name: fets-cache-vol
        - mountPath: /home/ubuntu
          name: fets-root-vol
        - mountPath: /workspace
          name: workspace-vol
      dnsPolicy: None
      dnsConfig:
        nameservers:
        - 8.8.8.8
        - 8.8.4.4
      volumes:
      - name: dshm
        emptyDir:
          medium: Memory
      - name: fets-cache-vol
        emptyDir: {}
      - name: fets-root-vol
        emptyDir: {}
      - name: workspace-vol
        emptyDir: {}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: topology.kubernetes.io/zone
                operator: NotIn
                values:
                - ucsd-suncave