apiVersion: v1
kind: Pod
metadata:
  name: fets-pod-fresh1
  namespace: gai-lina-group
spec:
  imagePullSecrets:
  - name: gitlab-registry-secret
  containers:
  - name: fets-container
    image: ghcr.io/fets-ai/front-end:1.0.2
    command: ["/bin/bash"]
    args: 
      - -c
      - |
        apt-get update && apt-get install -y git
        echo "Container started successfully!"
        tail -f /dev/null